### ISSUE TITLE
Don't see any of the exported metrics on New Relic

### ISSUE THREAD

**Issue by dusanslad** [corentinmusard/otel-cicd-action#50]
Hello,
I have tried using this action, but unfortunately i can't see any data exported in New Relic.
Here is my workflow:
```
name: Export workflow to New Relic

on:
  workflow_run:
    workflows: ['*']
    types: [completed]

jobs:
  otel-export-newrelic:
    permissions:
      contents: read # Required. To access the private repository
      actions: read # Required. To read workflow runs
      pull-requests: read # Optional. To read PR labels
      checks: read # Optional. To read run annotations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Export workflow to New Relic
        uses: corentinmusard/otel-cicd-action@v2
        
        with:
          otlpEndpoint: grpc://otlp.eu01.nr-data.net
          # Example value for NEWRELIC_OTLP_HEADERS:
          # api-key=YOUR_NEWRELIC_API_KEY
          otlpHeaders: ${{ secrets.NEWRELIC_OTLP_HEADERS }}
          githubToken: ${{ secrets.GHA_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
```
Where ${{ secrets.NEWRELIC_OTLP_HEADERS }} is saved as written in the comment line (api-key=YOUR_NEWRELIC_API_KEY)

This export workflow is being executed succesfully:

![Image](https://github.com/user-attachments/assets/4462eaec-92be-4f65-825e-cd840da88500)

Here is also whole log from this workflow:
[0_otel-export-newrelic.txt](https://github.com/user-attachments/files/18536596/0_otel-export-newrelic.txt)

And here is New Relic query i am using to get the data from New Relic:

![Image](https://github.com/user-attachments/assets/78cb7d82-5e85-4b40-9780-dc7a634ceb94)

What could be the problem why am I not able to see the exported data on New Relic?
